project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  
website: 
  navbar:
    left:
      - text: Tutoriais
        menu:
         - text: Heterogeneidade da paisagem
           href: https://resiliencia-climatica-brasil.github.io/diversity-resilience-python/apresentacao.html
         - text: Conectividade local 
         - text: Resiliência
           href: https://resiliencia-climatica-brasil.github.io/Relatorio_final/Resiliencia_da_paisagem.html
         
      - text: Downloads
        href: https://projeto-resiliencia-tnc.hub.arcgis.com   
      - text: Relatório Técnico
        href: https://resiliencia-climatica-brasil.github.io/Relatorio_final/     
  sidebar: 
    title: "Mapeamento de áreas resilientes a mudanças climáticas nos biomas brasileiros" 
    logo: figs/1667403883848_theme_logo.png     
    style: "docked"
    
               
  page-navigation: true
  favicon: figs/1667403883848_theme_logo.png
bibliography: bibliografia.bib
csl: citation_style.csl
lang: pt-br
format:
  html:
    theme: default
    css: styles.css   

