## Bases de dados e arquivos utilizados na análise

As bases de dados e arquivos utilizadas em cada etapa da análise são apresentadas abaixo.

### Uso e cobertura do solo

+ MapBiomas Coleção 8 - Ano 2021 [LINK COLEÇÃO 8]: (Projeto MapBiomas – Coleção 8 da Série Anual de Mapas de Cobertura e Uso da Terra do Brasil, acessado em outubro de 2023 através do link: https://storage.googleapis.com/mapbiomas-public/initiatives/brasil/collection_8/lclu/coverage/brasil_coverage_2022.tif)  

### Largura dos rios

<!-- 2024-03-04 remover
As informações sobre largura dos rios foram derivadas a partir das camadas de águas abertas do MapBiomas [@mapbiomas_project_collection_2020], a camada de bacias hidrográficas no nível 8 [Lehner &Grill (2013)]<!--COLOCAR NO ZOTERO--> e a camada de largura efetiva dos corpos d'água [Yamashida et al. 2014]. -->

+ MapBiomas Água: [INSERIR LINK BASE DE DADOS - PARA DOWNLOAD]

+ Bacias hidrográficas nível 8 (Lehner &Grill 2013): [INSERIR LINK BASE DE DADOS - PARA DOWNLOAD]

+ Largura efetiva dos corpos d'água (Yamashida et al. 2014): [INSERIR LINK BASE DE DADOS - PARA DOWNLOAD]

<!-- acho importante colocar também o link para o download, não somente a citação. No caso das bacias foi o HydroSHEDS? -->

### Infraestrutura de transporte e de energia

<!-- 2024-03-04 remover
As informações sobre infraestrutura de transporte foram originadas a partir das camadas de estradas pavimentadas, estradas não-pavimentadas e ferrovias fornecidas pelo Instituto Brasileiro de Geografia e Estatística (IBGE) (\[BCIM250, 2021\]) <!-- Isso é uma citação? --> (<https://www.ibge.gov.br/geociencias/cartas-e-mapas/bases-cartograficas-continuas/15759-brasil.html?=&t=downloads>).
As bases de infraestrutura de energia correspondem às camadas de aerogeradores, centrais geradoras de energia fotovoltaicas, linhas de transmissão de energia eólica e usinas termelétricas fornecidas pela Agência Nacional de Energia Elétrica (ANEEL) (<https://gisepeprd2.epe.gov.br/WebMapEPE/>) e a camada de linhas de transmissão de energia fornecida pelo IBGE (\[BCIM250, 2021\]).
-->

+ Estradas pavimentadas, estradas não-pavimentadas, ferrovias e linhas de transmissão de energia (IBGE - BCIM250, 2021):
<https://www.ibge.gov.br/geociencias/cartas-e-mapas/bases-cartograficas-continuas/15759-brasil.html?=&t=downloads>

+ Aerogeradores, centrais geradoras de energia fotovoltaicas, linhas de transmissão de energia eólica e usinas termelétricas (ANEEL):
<https://gisepeprd2.epe.gov.br/WebMapEPE/>

<!-- houve a necessidade de filtrar algum dados antes para fazer as análises, por exemplo na parte de energia, algum filtro foi aplicado para retirar informações que não eram necessárias? -->

### Filtro *kernel*

+ Filtro *kernel*: [ADICIONAR ARQUIVO TXT COM O FILTRO] 
